// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN16_X7t74Sexzj2Whrd2MAs2PUcdHS7E',
    appId: '1:519390265229:web:5129889402a4405977c7c4',
    messagingSenderId: '519390265229',
    projectId: 'ccfd-616af',
    authDomain: 'ccfd-616af.firebaseapp.com',
    storageBucket: 'ccfd-616af.firebasestorage.app',
    measurementId: 'G-W0RKCZZ4VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCthX0dt7FJbyeMjr-ikdUrNbj6rywBvAQ',
    appId: '1:519390265229:android:b4a1c1373490dc7177c7c4',
    messagingSenderId: '519390265229',
    projectId: 'ccfd-616af',
    storageBucket: 'ccfd-616af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvE3FduL9sMf3Oua2KZwzPOMB8Ki5oCGM',
    appId: '1:519390265229:ios:75ef369c2487e58177c7c4',
    messagingSenderId: '519390265229',
    projectId: 'ccfd-616af',
    storageBucket: 'ccfd-616af.firebasestorage.app',
    iosBundleId: 'com.example.ccd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvE3FduL9sMf3Oua2KZwzPOMB8Ki5oCGM',
    appId: '1:519390265229:ios:75ef369c2487e58177c7c4',
    messagingSenderId: '519390265229',
    projectId: 'ccfd-616af',
    storageBucket: 'ccfd-616af.firebasestorage.app',
    iosBundleId: 'com.example.ccd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN16_X7t74Sexzj2Whrd2MAs2PUcdHS7E',
    appId: '1:519390265229:web:7a64de2e5f0bb6e277c7c4',
    messagingSenderId: '519390265229',
    projectId: 'ccfd-616af',
    authDomain: 'ccfd-616af.firebaseapp.com',
    storageBucket: 'ccfd-616af.firebasestorage.app',
    measurementId: 'G-PJ79WP0ZL2',
  );
}
